[package]
name = "integrated-spreadsheet-environment"
version = "0.1.0"
authors = ["Korede Aderele <kaderele@gmail.com>"]
edition = "2018"

[dependencies]
yew = { git = "https://github.com/yewstack/yew", features = ["toml", "yaml", "msgpack", "cbor"] }
maplit = "1.0.2"
cargo-web = "0.6.26"
structopt = "0.2"
failure = "0.1"

[workspace]
members = ["frontend",]
